# Generated by Django 3.0.5 on 2020-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200507_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
